create table users
(
    id           bigint generated by default as identity,
    email        varchar(150) not null,
    first_name   varchar(100),
    last_name    varchar(100),
    phone_number varchar(15),
    user_status  integer,
    username     varchar(50)  not null,
    constraint pk_users primary key (id),
    constraint uk_users_username unique (username),
    constraint uk_users_email unique (email)
);

CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_users_email ON users (email);
